
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.proyecto;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int DOSPUNTOS = 64;
  public static final int CURP = 38;
  public static final int R_FUNC = 4;
  public static final int ASG_MUL = 51;
  public static final int SIMBOLO = 31;
  public static final int R_PROCS = 5;
  public static final int R_TEXTO = 14;
  public static final int ENTERO = 29;
  public static final int D_PAREN = 67;
  public static final int I_PAREN = 66;
  public static final int ASG_MOD = 53;
  public static final int RESTA = 42;
  public static final int R_PROC = 6;
  public static final int R_PARA = 26;
  public static final int R_FUNCS = 3;
  public static final int FECHA = 36;
  public static final int R_LOGICO = 15;
  public static final int R_FECHAHORA = 16;
  public static final int R_HORA = 18;
  public static final int NOT = 62;
  public static final int AND = 60;
  public static final int R_ROMPER = 28;
  public static final int MEN_IG = 59;
  public static final int IGUAL = 54;
  public static final int OR = 61;
  public static final int ASG_SUMA = 49;
  public static final int INC = 46;
  public static final int R_CURP = 19;
  public static final int DIV = 44;
  public static final int SUMA = 41;
  public static final int ID = 40;
  public static final int R_FECHA = 17;
  public static final int R_VARS = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 30;
  public static final int R_SIMBOLO = 13;
  public static final int R_RFC = 20;
  public static final int R_VAR = 8;
  public static final int R_INICIO = 9;
  public static final int error = 1;
  public static final int COMA = 65;
  public static final int MUL = 43;
  public static final int MENOR = 57;
  public static final int ASG_RESTA = 50;
  public static final int MOD = 45;
  public static final int R_DEVOLVER = 21;
  public static final int DESIGUAL = 55;
  public static final int ASG = 48;
  public static final int MAYOR = 56;
  public static final int R_SINO = 25;
  public static final int R_ENTONCES = 24;
  public static final int FECHAHORA = 35;
  public static final int PUNTO = 63;
  public static final int R_COMO = 22;
  public static final int R_ENTERO = 11;
  public static final int R_FIN = 10;
  public static final int FALSO = 33;
  public static final int R_SI = 23;
  public static final int R_PRINCIPAL = 2;
  public static final int R_DECIMAL = 12;
  public static final int VERDADERO = 34;
  public static final int R_MIENTRAS = 27;
  public static final int DEC = 47;
  public static final int TEXTO = 32;
  public static final int MAY_IG = 58;
  public static final int RFC = 39;
  public static final int HORA = 37;
  public static final int ASG_DIV = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "R_PRINCIPAL",
  "R_FUNCS",
  "R_FUNC",
  "R_PROCS",
  "R_PROC",
  "R_VARS",
  "R_VAR",
  "R_INICIO",
  "R_FIN",
  "R_ENTERO",
  "R_DECIMAL",
  "R_SIMBOLO",
  "R_TEXTO",
  "R_LOGICO",
  "R_FECHAHORA",
  "R_FECHA",
  "R_HORA",
  "R_CURP",
  "R_RFC",
  "R_DEVOLVER",
  "R_COMO",
  "R_SI",
  "R_ENTONCES",
  "R_SINO",
  "R_PARA",
  "R_MIENTRAS",
  "R_ROMPER",
  "ENTERO",
  "DECIMAL",
  "SIMBOLO",
  "TEXTO",
  "FALSO",
  "VERDADERO",
  "FECHAHORA",
  "FECHA",
  "HORA",
  "CURP",
  "RFC",
  "ID",
  "SUMA",
  "RESTA",
  "MUL",
  "DIV",
  "MOD",
  "INC",
  "DEC",
  "ASG",
  "ASG_SUMA",
  "ASG_RESTA",
  "ASG_MUL",
  "ASG_DIV",
  "ASG_MOD",
  "IGUAL",
  "DESIGUAL",
  "MAYOR",
  "MENOR",
  "MAY_IG",
  "MEN_IG",
  "AND",
  "OR",
  "NOT",
  "PUNTO",
  "DOSPUNTOS",
  "COMA",
  "I_PAREN",
  "D_PAREN"
  };
}

